controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    controller: App\Controller\MainController::homepage
    path: /
    stateless: true

app_logout:
    path: /logout
    methods: GET